---
- name: cisco router playbook show version and uptime
  hosts: routers
  gather_facts: false
  tasks:
  - name: show cisco router uptime (show how long the routers have been up)
    ios_command:
     commands: show version | i uptime
    register: output1
  - name: show ip addresses
    ios_command:
     commands: show ip int brief
    register: output2
  - name: print or display output
    debug:
     var: output1.stdout_lines,output2.stdout_lines
