---
- name: cisco router playbook show ip int brief
  hosts: routers
  gather_facts: false
  tasks:
  - name: show ip addresses
    ios_command:
     commands: show ip int brief
    register: output1
  - name: print or display output
    debug:
     var: output1.stdout_lines

